export const jobData: {
    employer_name: string;
    employer_logo: string | null;
    employer_website: string | null;
    employer_company_type: string | null;
    job_publisher: string;
    job_id: string;
    job_employment_type: 'FULLTIME' | 'PARTTIME' | 'CONTRACT' | 'TEMPORARY' | 'OTHER';
    job_title: string;
    job_apply_link: string;
    job_apply_is_direct: boolean;
    job_apply_quality_score: number;
    job_description: string;
    job_is_remote: boolean;
    job_posted_at_timestamp: number;
    job_posted_at_datetime_utc: string;
    job_city: string;
    job_state: string;
    job_country: string;
    job_latitude: number;
    job_longitude: number;
    job_benefits: string | null;
    job_google_link: string;
    job_offer_expiration_datetime_utc: string;
    job_offer_expiration_timestamp: number;
    job_required_experience: string | null;
    job_required_skills: string | null;
    job_required_education: string | null;
    job_experience_in_place_of_education: boolean;
    job_min_salary: number;
    job_max_salary: number;
    job_salary_currency: string;
    job_salary_period: 'YEAR' | 'MONTH' | 'WEEK' | 'HOUR';
    job_highlights: string | null;
    job_job_title: string | null;
    job_posting_language: string;
    job_onet_soc: string;
    job_onet_job_zone: string;
}[] = [
    {
        employer_name: "NextAfter",
        employer_logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3LtpFk_Qn5msyHfLis8HxKBBhhxla_ZNtS7bV&s=0",
        employer_website: "https://www.nextafter.com",
        employer_company_type: "Nonprofit",
        job_publisher: "LinkedIn",
        job_id: "DCi-37AXFUgAAAAAAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Front End Web Developer",
        job_apply_link: "https://www.linkedin.com/jobs/view/front-end-web-developer-at-nextafter-3621796979",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.5721,
        job_description: "At NextAfter, web developers are critical in allowing our nonprofit clients to escape the shackles of poorly designed software...",
        job_is_remote: false,
        job_posted_at_timestamp: 1685569007,
        job_posted_at_datetime_utc: "2023-05-31T21:36:47.000Z",
        job_city: "Plano",
        job_state: "TX",
        job_country: "US",
        job_latitude: 33.019844,
        job_longitude: -96.69888,
        job_benefits: "Health Insurance, Paid Time Off",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=web+developer+in+texas+usa",
        job_offer_expiration_datetime_utc: "2023-06-30T21:36:47.000Z",
        job_offer_expiration_timestamp: 1688161007,
        job_required_experience: "3+ years of experience in front-end development",
        job_required_skills: "JavaScript, HTML, CSS, A/B Testing, Google Analytics",
        job_required_education: "Bachelor’s degree in Computer Science or related field",
        job_experience_in_place_of_education: false,
        job_min_salary: 60000,
        job_max_salary: 70000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113400",
        job_onet_job_zone: "3"
    },
    {
        employer_name: "TechCorp",
        employer_logo: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/a-logo-design%7C-company-logo-template-7246ba946d6686a9a5b984a1e4380b1b_screen.jpg?ts=1665828706",
        employer_website: "https://www.techcorp.com",
        employer_company_type: "Technology",
        job_publisher: "Indeed",
        job_id: "ABc-47DYZHgAAAAAAAAAAA==",
        job_employment_type: "PARTTIME",
        job_title: "Backend Developer",
        job_apply_link: "https://www.indeed.com/jobs/view/backend-developer-at-techcorp-3621796980",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.6789,
        job_description: "As a Backend Developer at TechCorp, you will design and implement server-side logic for our web applications...",
        job_is_remote: true,
        job_posted_at_timestamp: 1685869007,
        job_posted_at_datetime_utc: "2023-06-03T14:45:07.000Z",
        job_city: "Austin",
        job_state: "TX",
        job_country: "US",
        job_latitude: 30.267153,
        job_longitude: -97.743057,
        job_benefits: "Remote Work, Flexible Hours",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=backend+developer+in+austin+texas",
        job_offer_expiration_datetime_utc: "2023-07-03T14:45:07.000Z",
        job_offer_expiration_timestamp: 1688461007,
        job_required_experience: "5+ years of experience in backend development",
        job_required_skills: "Node.js, Express, MongoDB, API Design",
        job_required_education: "Bachelor’s degree in Computer Science or related field",
        job_experience_in_place_of_education: false,
        job_min_salary: 50000,
        job_max_salary: 60000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113200",
        job_onet_job_zone: "4"
    },
    {
        employer_name: "CreativeMedia",
        employer_logo: 'https://media.istockphoto.com/id/1331491686/vector/element-design.jpg?s=612x612&w=0&k=20&c=QIMRS2IPiQyyTZJR_G1JAjH_ErBBkrDPtQe2GBNgm2w=',
        employer_website: null,
        employer_company_type: "Media",
        job_publisher: "Glassdoor",
        job_id: "XYx-93JKLHgAAAAAAAAAAA==",
        job_employment_type: "CONTRACT",
        job_title: "Graphic Designer",
        job_apply_link: "https://www.glassdoor.com/jobs/view/graphic-designer-at-creativemedia-3621796981",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.7894,
        job_description: "Join CreativeMedia as a Graphic Designer to create visually compelling content for our clients...",
        job_is_remote: false,
        job_posted_at_timestamp: 1686169007,
        job_posted_at_datetime_utc: "2023-06-06T10:30:07.000Z",
        job_city: "Los Angeles",
        job_state: "CA",
        job_country: "US",
        job_latitude: 34.052235,
        job_longitude: -118.243683,
        job_benefits: null,
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=graphic+designer+in+los+angeles+california",
        job_offer_expiration_datetime_utc: "2023-07-06T10:30:07.000Z",
        job_offer_expiration_timestamp: 1688761007,
        job_required_experience: "2+ years of experience in graphic design",
        job_required_skills: "Photoshop, Illustrator, InDesign, Creativity",
        job_required_education: "Associate’s degree in Graphic Design",
        job_experience_in_place_of_education: true,
        job_min_salary: 40000,
        job_max_salary: 45000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "27102400",
        job_onet_job_zone: "3"
    },
    {
        employer_name: "HealthFirst",
        employer_logo: "https://s3.amazonaws.com/cdn.designcrowd.com/blog/100-Famous-Brand%20Logos-From-The-Most-Valuable-Companies-of-2020/fedex.png",
        employer_website: "https://www.healthfirst.com",
        employer_company_type: "Healthcare",
        job_publisher: "Monster",
        job_id: "LMn-56TUVHgAAAAAAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Nurse Practitioner",
        job_apply_link: "https://www.monster.com/jobs/view/nurse-practitioner-at-healthfirst-3621796982",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.8456,
        job_description: "HealthFirst is seeking a dedicated Nurse Practitioner to provide compassionate care to our patients...",
        job_is_remote: false,
        job_posted_at_timestamp: 1686469007,
        job_posted_at_datetime_utc: "2023-06-09T16:20:07.000Z",
        job_city: "New York",
        job_state: "NY",
        job_country: "US",
        job_latitude: 40.712776,
        job_longitude: -74.005974,
        job_benefits: "Health Insurance, Retirement Plan, Paid Time Off",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=nurse+practitioner+in+new+york+city",
        job_offer_expiration_datetime_utc: "2023-07-09T16:20:07.000Z",
        job_offer_expiration_timestamp: 1689061007,
        job_required_experience: "5+ years of experience in nursing",
        job_required_skills: "Patient Care, Medical Diagnosis, Treatment Planning",
        job_required_education: "Master’s degree in Nursing",
        job_experience_in_place_of_education: false,
        job_min_salary: 80000,
        job_max_salary: 90000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "29117100",
        job_onet_job_zone: "5"
    },
    {
        employer_name: "EcoBuild",
        employer_logo: 'https://s3.amazonaws.com/cdn.designcrowd.com/blog/100-Famous-Brand%20Logos-From-The-Most-Valuable-Companies-of-2020/att-logo.png',
        employer_website: "https://www.ecobuild.com",
        employer_company_type: "Construction",
        job_publisher: "LinkedIn",
        job_id: "VWx-72MNQHgAAAAAAAAAAA==",
        job_employment_type: "TEMPORARY",
        job_title: "Site Manager",
        job_apply_link: "https://www.linkedin.com/jobs/view/site-manager-at-ecobuild-3621796983",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.6234,
        job_description: "EcoBuild is looking for a Site Manager to oversee construction projects from inception to completion...",
        job_is_remote: false,
        job_posted_at_timestamp: 1686769007,
        job_posted_at_datetime_utc: "2023-06-12T12:15:07.000Z",
        job_city: "San Francisco",
        job_state: "CA",
        job_country: "US",
        job_latitude: 37.774929,
        job_longitude: -122.419418,
        job_benefits: "Travel Reimbursement",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=site+manager+in+san+francisco+california",
        job_offer_expiration_datetime_utc: "2023-07-12T12:15:07.000Z",
        job_offer_expiration_timestamp: 1689361007,
        job_required_experience: "10+ years of experience in construction management",
        job_required_skills: "Project Management, Safety Compliance, Leadership",
        job_required_education: "Bachelor’s degree in Civil Engineering or related field",
        job_experience_in_place_of_education: true,
        job_min_salary: 70000,
        job_max_salary: 80000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "11902100",
        job_onet_job_zone: "4"
    },
    {
        employer_name: "BioTech Labs",
        employer_logo: "https://example.com/biotechlabs-logo.png",
        employer_website: "https://www.biotechlabs.com",
        employer_company_type: "Pharmaceutical",
        job_publisher: "Indeed",
        job_id: "ABC-12XYZHgAAAAAAAAAAA==",
        job_employment_type: "CONTRACT",
        job_title: "Research Scientist",
        job_apply_link: "https://www.indeed.com/jobs/view/research-scientist-at-biotech-labs-3621796984",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.9123,
        job_description: "BioTech Labs is seeking a Research Scientist to contribute to groundbreaking drug discovery projects...",
        job_is_remote: true,
        job_posted_at_timestamp: 1687069007,
        job_posted_at_datetime_utc: "2023-06-15T09:40:07.000Z",
        job_city: "Boston",
        job_state: "MA",
        job_country: "US",
        job_latitude: 42.360081,
        job_longitude: -71.058884,
        job_benefits: "Remote Work, Health Insurance, Research Grants",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=research+scientist+in+boston+massachusetts",
        job_offer_expiration_datetime_utc: "2023-07-15T09:40:07.000Z",
        job_offer_expiration_timestamp: 1689661007,
        job_required_experience: "7+ years of experience in pharmaceutical research",
        job_required_skills: "Molecular Biology, Data Analysis, Clinical Trials",
        job_required_education: "PhD in Biology, Chemistry, or related field",
        job_experience_in_place_of_education: false,
        job_min_salary: 95000,
        job_max_salary: 120000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "19104100",
        job_onet_job_zone: "5"
    },
    {
        employer_name: "StartUp Co.",
        employer_logo: "https://example.com/startupco-logo.png",
        employer_website: null,
        employer_company_type: "Technology",
        job_publisher: "AngelList",
        job_id: "DEF-34UVWQHgAAAAAAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Full Stack Developer",
        job_apply_link: "https://www.angel.co/jobs/view/full-stack-developer-at-startup-co-3621796985",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.7321,
        job_description: "As a Full Stack Developer at StartUp Co., you will build and maintain scalable web applications...",
        job_is_remote: false,
        job_posted_at_timestamp: 1687369007,
        job_posted_at_datetime_utc: "2023-06-18T11:55:07.000Z",
        job_city: "San Diego",
        job_state: "CA",
        job_country: "US",
        job_latitude: 32.715736,
        job_longitude: -117.161087,
        job_benefits: "Equity, Health Insurance, Paid Time Off",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=full+stack+developer+in+san+diego+california",
        job_offer_expiration_datetime_utc: "2023-07-18T11:55:07.000Z",
        job_offer_expiration_timestamp: 1689961007,
        job_required_experience: "4+ years of experience in full stack development",
        job_required_skills: "JavaScript, Node.js, React, SQL",
        job_required_education: "Bachelor’s degree in Computer Science or related field",
        job_experience_in_place_of_education: true,
        job_min_salary: 80000,
        job_max_salary: 95000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "15113200",
        job_onet_job_zone: "4"
    },
    {
        employer_name: "EduLearn",
        employer_logo: "https://example.com/edulearn-logo.png",
        employer_website: "https://www.edulearn.com",
        employer_company_type: "Education",
        job_publisher: "LinkedIn",
        job_id: "GHI-56ABQHgAAAAAAAAAAA==",
        job_employment_type: "PARTTIME",
        job_title: "Online Tutor",
        job_apply_link: "https://www.linkedin.com/jobs/view/online-tutor-at-edulearn-3621796986",
        job_apply_is_direct: false,
        job_apply_quality_score: 0.8345,
        job_description: "EduLearn is hiring an Online Tutor to assist students in a variety of subjects remotely...",
        job_is_remote: true,
        job_posted_at_timestamp: 1687669007,
        job_posted_at_datetime_utc: "2023-06-21T08:10:07.000Z",
        job_city: "Chicago",
        job_state: "IL",
        job_country: "US",
        job_latitude: 41.878113,
        job_longitude: -87.629799,
        job_benefits: "Remote Work, Flexible Hours",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=online+tutor+in+chicago+illinois",
        job_offer_expiration_datetime_utc: "2023-07-21T08:10:07.000Z",
        job_offer_expiration_timestamp: 1690261007,
        job_required_experience: "3+ years of experience in online teaching",
        job_required_skills: "Subject Matter Expertise, Communication, Time Management",
        job_required_education: "Bachelor’s degree in Education or related field",
        job_experience_in_place_of_education: false,
        job_min_salary: 35000,
        job_max_salary: 50000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "25301100",
        job_onet_job_zone: "4"
    },
    {
        employer_name: "HealthCare Corp",
        employer_logo: "https://example.com/healthcarecorp-logo.png",
        employer_website: "https://www.healthcarecorp.com",
        employer_company_type: "Healthcare",
        job_publisher: "Glassdoor",
        job_id: "JKL-78CDEQHgAAAAAAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Medical Assistant",
        job_apply_link: "https://www.glassdoor.com/jobs/view/medical-assistant-at-healthcare-corp-3621796987",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.6789,
        job_description: "HealthCare Corp is seeking a Medical Assistant to support our clinical team...",
        job_is_remote: false,
        job_posted_at_timestamp: 1687969007,
        job_posted_at_datetime_utc: "2023-06-24T14:35:07.000Z",
        job_city: "Los Angeles",
        job_state: "CA",
        job_country: "US",
        job_latitude: 34.052235,
        job_longitude: -118.243683,
        job_benefits: "Health Insurance, Paid Time Off",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=medical+assistant+in+los+angeles+california",
        job_offer_expiration_datetime_utc: "2023-07-24T14:35:07.000Z",
        job_offer_expiration_timestamp: 1690561007,
        job_required_experience: "2+ years of experience in a medical office",
        job_required_skills: "Patient Care, Medical Terminology, EHR Software",
        job_required_education: "High school diploma or equivalent",
        job_experience_in_place_of_education: true,
        job_min_salary: 30000,
        job_max_salary: 40000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "31909200",
        job_onet_job_zone: "3"
    },
    {
        employer_name: "HealthCare Corp",
        employer_logo: "https://example.com/healthcarecorp-logo.png",
        employer_website: "https://www.healthcarecorp.com",
        employer_company_type: "Healthcare",
        job_publisher: "Glassdoor",
        job_id: "JKL-78CDEQHgAAAAAAAAAAA==",
        job_employment_type: "FULLTIME",
        job_title: "Medical Assistant",
        job_apply_link: "https://www.glassdoor.com/jobs/view/medical-assistant-at-healthcare-corp-3621796987",
        job_apply_is_direct: true,
        job_apply_quality_score: 0.6789,
        job_description: "HealthCare Corp is seeking a Medical Assistant to support our clinical team...",
        job_is_remote: false,
        job_posted_at_timestamp: 1687969007,
        job_posted_at_datetime_utc: "2023-06-24T14:35:07.000Z",
        job_city: "Los Angeles",
        job_state: "CA",
        job_country: "US",
        job_latitude: 34.052235,
        job_longitude: -118.243683,
        job_benefits: "Health Insurance, Paid Time Off",
        job_google_link: "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=medical+assistant+in+los+angeles+california",
        job_offer_expiration_datetime_utc: "2023-07-24T14:35:07.000Z",
        job_offer_expiration_timestamp: 1690561007,
        job_required_experience: "2+ years of experience in a medical office",
        job_required_skills: "Patient Care, Medical Terminology, EHR Software",
        job_required_education: "High school diploma or equivalent",
        job_experience_in_place_of_education: true,
        job_min_salary: 30000,
        job_max_salary: 40000,
        job_salary_currency: "USD",
        job_salary_period: "YEAR",
        job_highlights: null,
        job_job_title: null,
        job_posting_language: "en",
        job_onet_soc: "31909200",
        job_onet_job_zone: "3"
    }
]